env:
  global:
    - CC_TEST_REPORTER_ID=b73746f31da5aea4946e2ef162081cd7f71c9ab5f0a0f6f4ee848702f65ad5b1
language: ruby
rvm:
  - 2.5.1
services:
  - postgresql
before_script:
  - psql -c 'create database ride_sharing_app_test;' -U postgres
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
  - bundle exec rails db:migrate RAILS_ENV=test
script:
  - bundle exec rspec
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
  - bundle exec rake coveralls:push
